### ISSUE TITLE
Using larger backbone of Dino Model

### ISSUE THREAD

**Issue by rishabh-akridata** [KevinWangHP/Anomaly-Clustering#3]
Hello @KevinWangHP,
How can we use the larger backbone of the dino model instead of the current dino_vitbase8 ones?

Thanks

**Comment by KevinWangHP** [comment]
To use a larger backbone for the DINO model instead of the current dino_vitbase8, you should first check which backbones are specifically supported under Anomaly-Clustering/Anomaly-Clustering/models/patchcore/backbone.py. However, note that larger DINO backbones are not natively supported in this project.

That said, theoretically, any backbone with feature extraction capabilities can be applied, but you would need to ensure the feature dimensions align with the project requirements. Be sure to verify compatibility before proceeding.

**Comment by rishabh-akridata** [comment]
Okay, Thanks.
